fix: ssl cert error
Running the plugin results in the following error:

error: crowdin api: Post "https://api.crowdin.com/api/v2/projects/ID/translations/builds": tls: failed to verify certificate: x509: certificate signed by unknown authority

The scratch image does not contain the necessary root certificates to verify the certificate from crowdin.com. We need to copy them in before doing that.